# https://huggingface.co/Undi95/Mistral-11B-v0.1
slices:
  - sources:
      - model: davzoku/cria-llama2-7b-v1.3
        layer_range: [0, 24]
  - sources:
      - model: davzoku/cria-llama2-7b-v1.3
        layer_range: [8, 32]
merge_method: passthrough
dtype: bfloat16
